#!/usr/bin/env bash

ROOT="$(npm root)"
BASE=`dirname '$ROOT'`

STATICS="index.html manual.html"
# VERSION="$(date '+%Y.%m.%d')"
VERSION="2022.DAGSTUHL"

rm -rf "$BASE/dist"
"$ROOT/rescript/rescript" build -with-deps
mkdir -p "$BASE/dist"
node "$BASE/bundle.js"
echo "$STATICS" | xargs -t -n 1 -I % sh -c "cp '$BASE/src/%' '$BASE/dist/%'"
ls "$BASE/dist" | xargs -t -I % sed -i '.bak' "s/##VERSION##/$VERSION/g" "$BASE/dist/%"
rm $BASE/dist/*.bak
