#!/usr/bin/env bash

read -d '' PY_FMT << EOF
import sys
import json

with open(sys.argv[1], 'r') as f:
    given = f.read()
    parsed = json.loads(given)
    tidied = json.dumps(parsed, indent=2, sort_keys=False) + '\\\\n'
if given != tidied:
    print("Formatted", sys.argv[1])
    with open(sys.argv[1], 'w') as f:
        f.write(tidied)
EOF

rg --files --type json | xargs -I file python3 -c "$PY_FMT" file
